### PR TITLE
refactor: load only template component without styles 

### PR DESCRIPTION
**Pull request by irustm**
If we only call getTemplateAst() method, we do not need to get all the styles for this componen with getResolvedMetadata() method.

If getResolvedMetadata was called in advance, it will be taken from the cache.
#11

### CODE REVIEW

**Comment by mgechev** [comment]
Yep, the optimization makes sense. Would you only update the commit message to reflect what you've changed?

**Comment by irustm** [comment]
If we only call `getTemplateAst()` method, we do not need to get all the styles for this componen with `getResolvedMetadata()` method. 

If `getResolvedMetadata` was called in advance, it will be taken from the cache.

**Comment by irustm** [comment]
@mgechev 
Can you release a patch version? That would be very helpful for [ngx-translate-migrate](https://github.com/irustm/ngx-translate-migrate)

**Comment by mgechev** [comment]
I can't build the project. Maybe dependency mismatch?

**Pull request merged**
